Al vf
nonpartisan-redistricting-datahub/Processing-Requests pull request #31
Opened 2023-06-15 18:43 UTC by peter-redistricting-data-hub

[al_20230403_vf_precs.zip](https://github.com/nonpartisan-redistricting-datahub/Processing-Requests/files/11761483/al_20230403_vf_precs.zip)

Please find the file attached

2023-06-15 20:31 UTC, rdhlily commented on Alabama_Precincts_VF_06_15_23/Alabama_Precincts_VF_06_15_23.ipynb
> +    "## Links to datasets used:\n",
Since the first thing is not a link can just say "Datasets used:"

2023-06-15 20:38 UTC, rdhlily commented on Alabama_Precincts_VF_06_15_23/Alabama_Precincts_VF_06_15_23.ipynb
> +  {
extra cell

2023-06-15 20:39 UTC, rdhlily requested changes
Very minor comments added. Code/processing looks good! Just file/readme items to address before posting file

2023-06-16 13:52 UTC, peter-redistricting-data-hub commented
[al_20230403_vf_precs.zip](https://github.com/nonpartisan-redistricting-datahub/Processing-Requests/files/11770957/al_20230403_vf_precs.zip)

Made those changes and here's the updated file!

2023-06-30 17:24 UTC, peter-redistricting-data-hub commented
@rdhlily can i just approve this?

2023-06-30 17:31 UTC, merged

2023-06-30 17:31 UTC, rdhlily commented
Yes, just did that, sorry!